# Site settings
title: mejariamol-Software Developer
description: Amol Mejari website
#baseurl: "/" # the subpath of your site, e.g. /blog
#url: "http://mejariamol.github.com" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Amol Mejari
user_description: I am an open source enthusiast. It always felt like I belong here. I like to learn new technologies and use them. I have had worked on android during Google Summer of Code 2017 as a student developer. Currently, I am into web development using modern JS frameworks.
user_title: Software Developer
email: mejariamol@gmail.com
twitter_username: mejariamol
github_username:  mejariamol
gplus_username:  mejariamol

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
